name: build
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Make gradlew Executable
        run: chmod +x gradlew
      - name: Build
        run: ./gradlew build -x test
      - name: Test
        run: ./gradlew check
      - name: Post Discord Status
        uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_ACTIONS_WEBHOOK }}
          username: Spectral
          avatar_url: https://i.imgur.com/2snlXOl.png