name: publish
on:
  release:
    types: [published]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - run: chmod +x gradlew
      - run: ./gradlew build -x test
      - run: ./gradlew publish
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_TOKEN: ${{ secrets.MAVEN_TOKEN }}
      - uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_ACTIONS_WEBHOOK }}
          username: Spectral
          avatar_url: https://i.imgur.com/2snlXOl.png
          noprefix: true
          title: Release Published
          description: A new release was published to maven repo for the `asm` project.
